import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const sql=readFileSync('supabase/migrations/001_school.sql','utf8');
test('Database: enrollment, grading, promotion, privacy, role restrictions, audit',async()=>{
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid,bucket_id text);alter table storage.objects enable row level security;`);
 await db.exec(sql);
 await db.exec(`grant usage on schema public,auth to authenticated,anon;grant select,insert,delete on all tables in schema public to authenticated;grant update on all tables in schema public to authenticated;revoke update on grades from authenticated;grant update(q1,q2,q3,q4) on grades to authenticated;grant select on all tables in schema public to anon;grant usage on all sequences in schema public to authenticated;
 insert into auth.users values('00000000-0000-0000-0000-000000000001'),('00000000-0000-0000-0000-000000000002'),('00000000-0000-0000-0000-000000000003');
 insert into profiles values('00000000-0000-0000-0000-000000000001','Admin','admin',true),('00000000-0000-0000-0000-000000000002','Teacher','teacher',true),('00000000-0000-0000-0000-000000000003','Other','teacher',false);
 select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000001',false);set role authenticated;`);
 const one=async(query:string,args:any[]=[])=>((await db.query(query,args)).rows[0] as any);
 const y=await one(`insert into school_years(name,active) values('2026–2027',true) returning id`);
 const y2=await one(`insert into school_years(name) values('2027–2028') returning id`);
 const g=await one(`select id from grade_levels where rank=1`),g2=await one(`select id from grade_levels where rank=2`);
 const s=await one(`insert into sections(name,grade_level_id,school_year_id) values('A',$1,$2) returning id`,[g.id,y.id]);
 const s2=await one(`insert into sections(name,grade_level_id,school_year_id) values('B',$1,$2) returning id`,[g2.id,y2.id]);
 const subject=await one(`insert into subjects(name,grade_level_id) values('Math',$1) returning id`,[g.id]);
 await db.query(`insert into subjects(name,grade_level_id) values('Math 2',$1)`,[g2.id]);
 const link=await one(`insert into enrollment_links(title,school_year_id,allowed_grade_ids,opens_at,closes_at) values('Enrollment',$1,array[$2::uuid],now(),now()+interval '1 day') returning id`,[y.id,g.id]);
 const a=await one(`insert into applications(link_id,grade_level_id,lrn,first_name,last_name,birth_date,sex,address,contact,guardian_name,guardian_contact,enrollment_type) values($1,$2,'123456789012','Ana','Cruz','2019-01-01','Female','Masbate','123','Parent','123','New') returning id`,[link.id,g.id]);
 await assert.rejects(()=>db.query('select approve_application($1,$2)',[a.id,s2.id]),/section/i);
 await db.query('select approve_application($1,$2)',[a.id,s.id]);
 const n=await one('select * from enrollments');
 assert.equal((await one('select status from applications')).status,'Enrolled');
 assert.equal((await db.query('select * from grades')).rows.length,1);
 await assert.rejects(()=>db.query('select approve_application($1,$2)',[a.id,s.id]),/cannot/i);
 await assert.rejects(()=>db.query('select promote_student($1,$2,$3)',[n.id,y2.id,s2.id]),/passing/i);
 await db.query(`insert into assignments(teacher_id,section_id,subject_id) values('00000000-0000-0000-0000-000000000002',$1,$2)`,[s.id,subject.id]);
 await db.exec(`reset role;select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000002',false);set role authenticated;`);
 assert.equal((await db.query('select * from students')).rows.length,1);
 await db.query('update grades set q1=80,q2=81,q3=82,q4=83');assert.equal((await one('select final_grade from grades')).final_grade,'82');
 await assert.rejects(()=>db.query('update grades set subject_id=$1',[subject.id]),/permission/i);
 await assert.rejects(()=>db.query('select promote_student($1,$2,$3)',[n.id,y2.id,s2.id]),/Admin/i);
 await db.exec(`reset role;select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000003',false);set role authenticated;`);
 assert.equal((await db.query('select * from students')).rows.length,0);assert.equal((await db.query('select * from grades')).rows.length,0);
 await db.exec('reset role;set role anon;');assert.equal((await db.query('select * from applications')).rows.length,0);assert.equal((await db.query('select * from students')).rows.length,0);
 await db.exec(`reset role;select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000001',false);set role authenticated;`);
 await db.query('select promote_student($1,$2,$3)',[n.id,y2.id,s2.id]);assert.equal((await db.query('select * from enrollments')).rows.length,2);assert.equal((await db.query('select * from grades')).rows.length,2);
 await db.query('update subjects set name=$1 where id=$2',['Mathematics',subject.id]);
 await assert.rejects(()=>db.query('update subjects set grade_level_id=$1 where id=$2',[g2.id,subject.id]),/history/i);
 await assert.rejects(()=>db.query('update sections set school_year_id=$1 where id=$2',[y2.id,s.id]),/history/i);
 await db.query("insert into assignments(teacher_id,section_id,subject_id) values('00000000-0000-0000-0000-000000000003',$1,$2)",[s.id,subject.id]);
 await db.exec("reset role;select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000003',false);set role authenticated;");
 await db.query('update grades set q1=1 where enrollment_id=$1',[n.id]);assert.equal((await one('select q1 from grades where enrollment_id=$1',[n.id])).q1,'80');
 await db.exec("reset role;select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000001',false);set role authenticated;");
 assert.ok((await db.query('select * from audit_logs')).rows.length>10);
 await db.close();
});
