import {useEffect,useRef,useState} from 'react';
import {MessageCircle,HelpCircle,X} from 'lucide-react';
import {Language,Topic,translations,topicKeys,guideTextKeys} from './enrollment-i18n';
export function FieldHelp({topic,language,open}:{topic:Topic;language:Language;open:(topic:Topic)=>void}){const t=translations[language];return <button className="field-help" type="button" aria-label={`${t.help} ${t[topic]}`} onClick={()=>open(topic)}><HelpCircle size={16}/></button>}
export function EnrollmentGuide({language,onLanguage,topic,onTopic,open,onOpen}:{language:Language;onLanguage:(v:Language)=>void;topic:Topic;onTopic:(v:Topic)=>void;open:boolean;onOpen:(v:boolean)=>void}){
 const t=translations[language];const [search,setSearch]=useState('');const [visible,setVisible]=useState(open);const trigger=useRef<HTMLButtonElement>(null);const close=useRef<HTMLButtonElement>(null);const wasOpen=useRef(false);
 useEffect(()=>{if(open){setVisible(true);const focusTimer=setTimeout(()=>close.current?.focus(),0);const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')onOpen(false)};document.addEventListener('keydown',escape);wasOpen.current=true;return()=>{clearTimeout(focusTimer);document.removeEventListener('keydown',escape)}}else if(wasOpen.current){trigger.current?.focus();wasOpen.current=false;const timer=setTimeout(()=>setVisible(false),window.matchMedia?.('(prefers-reduced-motion: reduce)').matches?0:160);return()=>clearTimeout(timer)}},[open]);
 const topics=topicKeys.filter(k=>(t[k]+' '+t[guideTextKeys[k]]).toLowerCase().includes(search.toLowerCase()));
 return <div className="enrollment-help" lang={language==='fil'?'fil':'en'}>{(open||visible)&&<section id="enrollment-guide" aria-hidden={!open} inert={!open} className={'guide-panel'+(!open?' is-closing':'')} role="dialog" aria-modal="false" aria-labelledby="guide-title"><div className="guide-heading"><h2 id="guide-title">{t.guide}</h2><button type="button" ref={close} aria-label={t.close} onClick={()=>onOpen(false)}><X size={18}/></button></div><div className="guide-languages" role="group" aria-label="English / Filipino"><button type="button" aria-pressed={language==='en'} onClick={()=>onLanguage('en')}>English</button><button type="button" aria-pressed={language==='fil'} onClick={()=>onLanguage('fil')}>Filipino</button></div><div className="guide-current"><small>{t.stepHelp}</small><h3>{t[topic]}</h3><p>{String(t[guideTextKeys[topic]])}</p></div><label className="guide-search">{t.search}<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="guide-topics">{topics.map(k=><button type="button" key={k} aria-pressed={topic===k} onClick={()=>onTopic(k)}>{t[k]}</button>)}</div></section>}<button className="guide-trigger" type="button" ref={trigger} aria-label={t.help} aria-expanded={open} aria-controls="enrollment-guide" onClick={()=>onOpen(!open)}><MessageCircle size={25}/><span>{t.help}</span></button></div>
}
