export type Language='en'|'fil';
export type Topic='type'|'lrn'|'learner'|'guardian'|'address'|'grade'|'previous'|'documents'|'confirmation'|'errors';
const en={
 guide:'RZM Enrollment Guide',help:'Need help?',close:'Close guide',search:'Search help topics',stepHelp:'Help for this step',
 type:'Enrollment type',lrn:'Learner Reference Number (LRN)',learner:'Learner information',guardian:'Parent / guardian',address:'Home address',grade:'Grade level',previous:'Previous school',documents:'Required documents',confirmation:'Review and confirmation',errors:'Common form errors',
 guideType:'Choose New only for a first-time enrollee. Choose Returning for a learner enrolled here before, or Transferee for a learner coming from another school. Having no LRN does not make a returning learner new.',
 guideLrn:'An LRN is a unique 12-digit number assigned through DepEd. Look for it on the report card or school records. Keep leading zeros. Ask the previous school if you do not know it. This site never invents an official LRN.',
 guideLearner:'Copy the learner’s name, birth date and sex from official documents. Use the learner’s details, not the parent’s. Check spelling before continuing.',
 guideGuardian:'Enter the full name of the parent or legal guardian and a working contact number the school can reach.',
 guideAddress:'Write the house or street, barangay, municipality or city, and province. Include useful location details if there is no street number.',
 guideGrade:'Select the grade the learner is applying for. Only grades offered by this enrollment link are shown. Contact the school if the correct grade is missing.',
 guidePrevious:'Returning or transferring learners should provide the name of their previous school. First-time learners may leave it empty.',
 guideDocuments:'Upload clear, readable files: JPG/PNG for the learner’s photo; JPG/PNG/PDF for the birth certificate. Each must be 5 MB or smaller. Check that the entire document is visible.',
 guideConfirmation:'Check all details and complete the verification before submitting. A saved draft is not an application. After successful submission, keep the reference number for school follow-up. A temporary reference is not an official LRN.',
 guideErrors:'Complete required fields and upload both documents. An official LRN must have exactly 12 digits. If an application already exists for this school year, contact the school. Offline LRN checks are pending; the server checks again during submission.',
 first_name:'First name',last_name:'Last name',birth_date:'Birth date',sex:'Sex',grade_level_id:'Grade level',contact:'Contact number',guardian_name:'Parent / guardian’s full name',guardian_contact:'Parent / guardian’s contact number',previous_school:'Previous school',extra_answers:'Additional answers',enrollment_type:'Enrollment type',
 newLearner:'New / first-time learner',returnLearner:'Returning / transferring learner',returning:'Returning learner',transferee:'Transferring learner',firstQuestion:'Is this the learner’s first enrollment, without an LRN assigned by DepEd?',hasQuestion:'Does the learner already have an official LRN?',yes:'Yes',no:'No / I do not know it',pendingAssignment:'LRN Pending Assignment',pendingExplanation:'You can continue without an official LRN. A temporary reference will be generated after successful submission.',unknownExplanation:'Ask the previous school for the LRN. You can continue, but staff must verify the learner before approval. This does not register the learner as new.',temporary:'Temporary enrollment reference — not an official LRN',
 required:'Required',optional:'Optional',select:'Select…',male:'Male',female:'Female',back:'Back',next:'Continue',submit:'Submit application',submitting:'Submitting…',step:'Step',of:'of',
 invalidLrn:'Please enter a valid 12-digit Learner Reference Number.',checking:'Checking LRN…',eligible:'LRN format is valid. The school will verify it during submission.',existingNew:'This LRN is already registered. Please contact the school or select the correct returning/transferring enrollment type.',existingReturn:'This LRN needs staff verification. Your application may continue for authorized re-enrollment review.',duplicate:'An active application for this LRN already exists for this school year. Contact the school for assistance.',pendingCheck:'LRN verification pending. A connection is needed; the server will check before accepting the application.',
 requiredError:'This field is required or incomplete. Please check the highlighted field before continuing.',missingDocument:'Please upload both required documents before submitting.',badDocument:'Use a JPG/PNG photo and a JPG/PNG/PDF birth certificate, each up to 5 MB.',consent:'I confirm these details are accurate and consent to the school processing them for enrollment and academic administration.',captchaMissing:'The school must configure submission verification. Contact the school office.',offlineSubmit:'You are offline. Save a draft on this device; reconnect to verify and submit. Your draft has not been submitted.',
 draftConsent:'Save my enrollment draft and documents on this device',draftPrivacy:'Use this only on a trusted device. Drafts are not submitted automatically.',draftSaved:'Draft saved on this device. It has not been submitted.',draftRestored:'Your locally saved draft was restored.',saveDraft:'Save draft now',clearDraft:'Delete local draft',clearConfirm:'Delete the draft and its documents from this device?',draftError:'Unable to save the draft locally. Keep this page open and retry, or contact the school.',
 received:'Application received',referenceNote:'Keep this reference number for school follow-up.',print:'Print confirmation',reviewNote:'Your application is pending school review. Contact the office for updates.',startAnother:'Start another application',anotherConfirm:'Start a different application? Keep the current confirmation first.',
 welcome:'Welcome to enrollment',welcomeText:'Start your application for',start:'Start enrollment',loading:'Loading enrollment details…',preparing:'Preparing your enrollment form',opening:'Opening your form…',wait:'Please wait a moment while we get everything ready.',intro:'Every learning journey starts with a first step.',introText:'Complete your learner’s enrollment application below.',secure:'Secure submission',six:'Six simple steps',assistance:'Need assistance? Contact the school office. Parents and learners do not need an account.',
 titles:['Learner information','Address & contact','Parent / guardian','Previous school','Required documents','Review & submit'],
 descriptions:['Use the details on the learner’s official documents.','Tell the school where the learner lives and how to contact you.','Add the parent or guardian the school should contact.','Share the previous school, if applicable.','Upload clear documents, up to 5 MB each.','Check all details before submitting.'],
 photo:'Learner photo',certificate:'Birth certificate',noLrnReview:'No official LRN provided — school verification may be required.',
 server:{LINK_UNAVAILABLE:'This enrollment link is closed or unavailable.',ORIGIN_NOT_ALLOWED:'The school must enable this website address for enrollment. Please contact the office.',INVALID_LRN:'Please enter a valid 12-digit Learner Reference Number.',INVALID_DETAILS:'Check the required learner information.',ACTIVE_LRN_APPLICATION:'An active application with this LRN already exists for this school year. Contact the school.',EXISTING_LRN_CONTACT_SCHOOL:'This LRN already belongs to a school record. Contact the school or use the returning/transferring workflow.',SUBMISSION_CHANGED:'A previous attempt may already be received. Keep your reference or contact the school before changing and resubmitting.',MISSING_DOCUMENTS:'Please upload both required documents.',INVALID_DOCUMENT:'Use JPG/PNG for the photo and JPG/PNG/PDF for the birth certificate.',DOCUMENT_TOO_LARGE:'Each document must be 5 MB or smaller.',REQUEST_TOO_LARGE:'The uploaded files are too large.',CAPTCHA_REQUIRED:'Please complete the submission verification again.',RATE_LIMITED:'Too many requests. Wait a minute before checking or submitting again.',INVALID_SUBMISSION:'Refresh the page to restore your submission attempt.',SERVICE_UNAVAILABLE:'Enrollment is temporarily unavailable. Your entries remain on this page. Please retry or contact the school.'}
};
const fil:typeof en={
 guide:'Gabay sa Pagpapatala ng RZM',help:'Kailangan ng tulong?',close:'Isara ang gabay',search:'Maghanap ng paksa',stepHelp:'Gabay para sa hakbang na ito',
 type:'Uri ng pagpapatala',lrn:'Learner Reference Number (LRN)',learner:'Impormasyon ng mag-aaral',guardian:'Magulang / tagapag-alaga',address:'Tirahan',grade:'Baitang',previous:'Dating paaralan',documents:'Mga kailangang dokumento',confirmation:'Pagsusuri at pagkumpirma',errors:'Karaniwang pagkakamali',
 guideType:'Piliin ang Bago kung unang beses pa lang magpapatala. Piliin ang Nagbabalik kung dati nang nag-aral dito, o Lilipat kung galing sa ibang paaralan. Ang kawalan ng LRN ay hindi nangangahulugang bagong mag-aaral siya.',
 guideLrn:'Ang LRN ay natatanging 12-digit na numero na ibinibigay sa mag-aaral sa pamamagitan ng DepEd. Makikita ito sa report card o rekord ng paaralan. Isama ang mga zero sa unahan. Magtanong sa dating paaralan kung hindi ito alam. Hindi gumagawa ng opisyal na LRN ang website na ito.',
 guideLearner:'Kopyahin ang pangalan, petsa ng kapanganakan at kasarian mula sa opisyal na dokumento. Detalye ng mag-aaral ang ilagay, hindi ng magulang. Suriin ang baybay bago magpatuloy.',
 guideGuardian:'Ilagay ang buong pangalan ng magulang o legal na tagapag-alaga at ang numerong matatawagan ng paaralan.',
 guideAddress:'Ilagay ang bahay o kalye, barangay, bayan o lungsod, at lalawigan. Magdagdag ng malinaw na palatandaan kung walang numero ang bahay.',
 guideGrade:'Piliin ang baitang na papasukan ng mag-aaral. Mga baitang na sakop lang ng link na ito ang makikita. Makipag-ugnayan sa paaralan kung wala ang tamang baitang.',
 guidePrevious:'Para sa nagbabalik o lilipat na mag-aaral, ilagay ang pangalan ng dating paaralan. Maaaring iwanang walang laman kung unang beses pa lang mag-aaral.',
 guideDocuments:'Mag-upload ng malinaw at nababasang file: JPG/PNG para sa larawan ng mag-aaral; JPG/PNG/PDF para sa birth certificate. Bawat file ay hanggang 5 MB lamang. Tiyaking kita ang buong dokumento.',
 guideConfirmation:'Suriin ang mga detalye at kumpletuhin ang beripikasyon bago isumite. Ang naka-save na draft ay hindi pa aplikasyon. Pagkatapos ng matagumpay na pagsusumite, itago ang reference number. Ang pansamantalang reference ay hindi opisyal na LRN.',
 guideErrors:'Sagutan ang mga kailangang bahagi at i-upload ang dalawang dokumento. Dapat eksaktong 12 digit ang opisyal na LRN. Kung may aplikasyon na para sa taong-panuruan na ito, makipag-ugnayan sa paaralan. Kapag offline, hindi pa nasusuri ang LRN; susuriin muli ng server bago tanggapin.',
 first_name:'Unang pangalan',last_name:'Apelyido',birth_date:'Petsa ng kapanganakan',sex:'Kasarian',grade_level_id:'Baitang',contact:'Numero ng telepono',guardian_name:'Buong pangalan ng magulang / tagapag-alaga',guardian_contact:'Numero ng magulang / tagapag-alaga',previous_school:'Dating paaralan',extra_answers:'Karagdagang sagot',enrollment_type:'Uri ng pagpapatala',
 newLearner:'Bago / unang pagpapatala',returnLearner:'Nagbabalik / lilipat na mag-aaral',returning:'Nagbabalik na mag-aaral',transferee:'Lilipat na mag-aaral',firstQuestion:'Ito ba ang unang pagpapatala ng mag-aaral at wala pa siyang LRN na ibinigay ng DepEd?',hasQuestion:'May opisyal na LRN na ba ang mag-aaral?',yes:'Oo',no:'Wala / Hindi ko alam',pendingAssignment:'Naghihintay ng Opisyal na LRN',pendingExplanation:'Maaaring magpatuloy kahit wala pang opisyal na LRN. Bibigyan ng pansamantalang reference pagkatapos ng matagumpay na pagsusumite.',unknownExplanation:'Itanong ang LRN sa dating paaralan. Maaaring magpatuloy, ngunit kailangang suriin muna ng paaralan ang mag-aaral bago aprubahan. Hindi siya ituturing na bagong mag-aaral.',temporary:'Pansamantalang reference sa pagpapatala — hindi opisyal na LRN',
 required:'Kailangan',optional:'Opsyonal',select:'Pumili…',male:'Lalaki',female:'Babae',back:'Bumalik',next:'Magpatuloy',submit:'Isumite ang aplikasyon',submitting:'Isinusumite…',step:'Hakbang',of:'sa',
 invalidLrn:'Mangyaring maglagay ng wastong 12-digit Learner Reference Number.',checking:'Sinusuri ang LRN…',eligible:'Wasto ang anyo ng LRN. Susuriin ito ng paaralan sa pagsusumite.',existingNew:'Nakarehistro na ang LRN na ito. Makipag-ugnayan sa paaralan o piliin ang tamang uri para sa nagbabalik o lilipat na mag-aaral.',existingReturn:'Kailangang beripikahin ng paaralan ang LRN na ito. Maaaring magpatuloy ang aplikasyon para sa pagsusuri ng muling pagpapatala.',duplicate:'May aktibong aplikasyon na para sa LRN na ito sa taong-panuruan na ito. Makipag-ugnayan sa paaralan para sa tulong.',pendingCheck:'Hindi pa nasusuri ang LRN. Kailangan ng koneksyon; susuriin ito ng server bago tanggapin ang aplikasyon.',
 requiredError:'Kailangan o kulang ang bahaging ito. Suriin ang nakamarkang bahagi bago magpatuloy.',missingDocument:'I-upload muna ang dalawang kailangang dokumento bago isumite.',badDocument:'Gumamit ng JPG/PNG para sa larawan at JPG/PNG/PDF para sa birth certificate, hanggang 5 MB bawat isa.',consent:'Pinatutunayan kong tama ang mga detalye at pumapayag akong gamitin ng paaralan ang mga ito para sa pagpapatala at pangangasiwa ng mga rekord.',captchaMissing:'Kailangang ayusin ng paaralan ang beripikasyon sa pagsusumite. Makipag-ugnayan sa opisina.',offlineSubmit:'Offline ka ngayon. Mag-save ng draft sa device na ito at kumonekta muli para beripikahin at isumite. Hindi pa naipapasa ang draft.',
 draftConsent:'I-save ang draft at mga dokumento sa device na ito',draftPrivacy:'Gamitin lamang sa pinagkakatiwalaang device. Hindi awtomatikong ipinapasa ang draft.',draftSaved:'Naka-save ang draft sa device na ito. Hindi pa ito naipapasa.',draftRestored:'Naibalik ang iyong naka-save na draft.',saveDraft:'I-save ang draft ngayon',clearDraft:'Burahin ang lokal na draft',clearConfirm:'Burahin ang draft at mga dokumento sa device na ito?',draftError:'Hindi na-save ang draft sa device. Panatilihing bukas ang pahina at subukang muli o makipag-ugnayan sa paaralan.',
 received:'Natanggap ang aplikasyon',referenceNote:'Itago ang reference number para sa pakikipag-ugnayan sa paaralan.',print:'I-print ang kumpirmasyon',reviewNote:'Naghihintay ng pagsusuri ng paaralan ang aplikasyon. Makipag-ugnayan sa opisina para sa update.',startAnother:'Magsimula ng ibang aplikasyon',anotherConfirm:'Magsimula ng ibang aplikasyon? Itago muna ang kasalukuyang kumpirmasyon.',
 welcome:'Maligayang pagdating sa pagpapatala',welcomeText:'Simulan ang aplikasyon para sa',start:'Simulan ang pagpapatala',loading:'Kinukuha ang detalye ng pagpapatala…',preparing:'Inihahanda ang form ng pagpapatala',opening:'Binubuksan ang form…',wait:'Sandali lamang habang inihahanda namin ang lahat.',intro:'Nagsisimula ang pagkatuto sa unang hakbang.',introText:'Sagutan ang aplikasyon sa pagpapatala ng iyong mag-aaral.',secure:'Ligtas na pagsusumite',six:'Anim na simpleng hakbang',assistance:'Kailangan ng tulong? Makipag-ugnayan sa opisina ng paaralan. Hindi kailangan ng account ang magulang at mag-aaral.',
 titles:['Impormasyon ng mag-aaral','Tirahan at kontak','Magulang / tagapag-alaga','Dating paaralan','Mga kailangang dokumento','Suriin at isumite'],
 descriptions:['Gamitin ang detalye sa opisyal na dokumento ng mag-aaral.','Ipaalam kung saan nakatira at paano makokontak ang mag-aaral.','Ilagay ang magulang o tagapag-alagang kokontakin ng paaralan.','Ibigay ang dating paaralan kung mayroon.','Mag-upload ng malinaw na dokumento, hanggang 5 MB bawat isa.','Suriin ang lahat ng detalye bago isumite.'],
 photo:'Larawan ng mag-aaral',certificate:'Birth certificate',noLrnReview:'Walang opisyal na LRN na ibinigay — maaaring kailangan ng beripikasyon ng paaralan.',
 server:{LINK_UNAVAILABLE:'Sarado o hindi magagamit ang link ng pagpapatala.',ORIGIN_NOT_ALLOWED:'Kailangang pahintulutan ng paaralan ang address ng website na ito. Makipag-ugnayan sa opisina.',INVALID_LRN:'Maglagay ng wastong 12-digit Learner Reference Number.',INVALID_DETAILS:'Suriin ang mga kailangang impormasyon ng mag-aaral.',ACTIVE_LRN_APPLICATION:'May aktibong aplikasyon na para sa LRN na ito sa taong-panuruan na ito. Makipag-ugnayan sa paaralan.',EXISTING_LRN_CONTACT_SCHOOL:'May rekord na para sa LRN na ito. Makipag-ugnayan sa paaralan o gamitin ang proseso para sa nagbabalik o lilipat.',SUBMISSION_CHANGED:'Maaaring natanggap na ang naunang pagsubok. Itago ang reference o makipag-ugnayan sa paaralan bago baguhin at isumite muli.',MISSING_DOCUMENTS:'I-upload ang dalawang kailangang dokumento.',INVALID_DOCUMENT:'Gumamit ng JPG/PNG para sa larawan at JPG/PNG/PDF para sa birth certificate.',DOCUMENT_TOO_LARGE:'Hanggang 5 MB lamang bawat dokumento.',REQUEST_TOO_LARGE:'Masyadong malaki ang mga na-upload na file.',CAPTCHA_REQUIRED:'Kumpletuhin muli ang beripikasyon bago isumite.',RATE_LIMITED:'Masyadong maraming kahilingan. Maghintay ng isang minuto bago subukang muli.',INVALID_SUBMISSION:'I-refresh ang pahina para maibalik ang iyong pagsubok sa pagsusumite.',SERVICE_UNAVAILABLE:'Pansamantalang hindi magagamit ang pagpapatala. Nananatili ang iyong mga sagot sa pahina. Subukang muli o makipag-ugnayan sa paaralan.'}
};
export const translations={en,fil};
export const stepTopics:Topic[]=['learner','address','guardian','previous','documents','confirmation'];
export const topicKeys:Topic[]=['type','lrn','learner','guardian','address','grade','previous','documents','confirmation','errors'];
export const guideTextKeys:Record<Topic,keyof typeof en>={type:'guideType',lrn:'guideLrn',learner:'guideLearner',guardian:'guideGuardian',address:'guideAddress',grade:'guideGrade',previous:'guidePrevious',documents:'guideDocuments',confirmation:'guideConfirmation',errors:'guideErrors'};
export function initialLanguage():Language{try{return localStorage.getItem('rzm-guide-language')==='fil'?'fil':'en'}catch{return 'en'}}
export const lrnDigits=(value:string)=>value.replace(/\D/g,'').slice(0,12);
