import React,{useEffect,useRef,useState} from 'react';
import {ArrowRight,Check,ClipboardList,Download,Printer,Shield} from 'lucide-react';
import {configured,Row} from './lib';
import {get,put,request,transaction,uuid} from './local-db';
import {EnrollmentGuide,FieldHelp} from './EnrollmentGuide';
import {initialLanguage,Language,lrnDigits,stepTopics,Topic,translations} from './enrollment-i18n';
import {useLrnCheck} from './useLrnCheck';
import './enrollment-guide.css';
import './enrollment-form.css';
const initialForm=()=>({enrollment_type:'New',has_lrn:false,lrn:''} as Row);
const fieldTopics:Record<string,Topic>={lrn:'lrn',grade_level_id:'grade',guardian_name:'guardian',guardian_contact:'guardian',previous_school:'previous',address:'address',first_name:'learner',last_name:'learner',birth_date:'learner',sex:'learner',contact:'address'};
export function PublicEnrollment({token}:{token:string}){
 const [language,setLanguage]=useState<Language>(initialLanguage),[guideOpen,setGuideOpen]=useState(false),[topic,setTopic]=useState<Topic>('learner');const t=translations[language];
 const [info,setInfo]=useState<Row|null>(null),[errorKey,setErrorKey]=useState(''),[step,setStep]=useState(0),[form,setForm]=useState<Row>(initialForm),[files,setFiles]=useState<Record<string,File>>({}),[captcha,setCaptcha]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState<Row|null>(null);
 const [entryStage,setEntryStage]=useState<'welcome'|'loading'|'leaving'|'form'>('welcome');const [draftEnabled,setDraftEnabled]=useState(false),[draftReady,setDraftReady]=useState(false),[draftMessage,setDraftMessage]=useState('');const submission=useRef('');const [attemptReady,setAttemptReady]=useState(false);
 const endpoint=import.meta.env.VITE_SUPABASE_URL+'/functions/v1/public-enrollment?token='+encodeURIComponent(token);const lrnState=useLrnCheck(endpoint,String(form.lrn||''),form.enrollment_type,!!form.has_lrn);const blocked=lrnState==='existing_new'||lrnState==='duplicate_application';
 const error=errorKey?(t.server as Record<string,string>)[errorKey]||(t as any)[errorKey]||t.server.SERVICE_UNAVAILABLE:'';
 const help=(value:Topic)=>{setTopic(value);setGuideOpen(true)};const guide=<EnrollmentGuide language={language} onLanguage={v=>{setLanguage(v);try{localStorage.setItem('rzm-guide-language',v)}catch{}}} topic={topic} onTopic={setTopic} open={guideOpen} onOpen={setGuideOpen}/>;
 useEffect(()=>{let cancelled=false;void (async()=>{const cached=await get('meta','public-info:'+token);if(!cancelled&&cached)setInfo(cached.value);const attempt=await get('meta','public-attempt:'+token);if(cancelled)return;submission.current=attempt?.id||uuid();if(attempt?.result)setResult(attempt.result);if(!attempt)await put('meta',{key:'public-attempt:'+token,id:submission.current});if(cancelled)return;setAttemptReady(true);const draft=await get('drafts','public:'+token);if(draft&&!attempt?.result&&!cancelled){setForm(draft.form);setStep(Math.min(5,Math.max(0,draft.step||0)));setDraftEnabled(true);const restored:Record<string,File>={};for(const [key,file] of Object.entries(draft.files||{}) as [string,any][])restored[key]=new File([file.blob],file.name,{type:file.type,lastModified:file.lastModified});setFiles(restored);setDraftMessage('draftRestored');}if(!cancelled)setDraftReady(true)})().catch(()=>{if(!cancelled){setDraftReady(true);setErrorKey('draftError')}});return()=>{cancelled=true}},[token]);
 useEffect(()=>{if(!configured){setErrorKey('SERVICE_UNAVAILABLE');return;}let cancelled=false;const controller=new AbortController();const load=()=>{if(!navigator.onLine)return;void fetch(endpoint,{headers:{apikey:import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY},signal:controller.signal}).then(async r=>{const body=await r.json();if(!r.ok)throw Error(body.errorCode||'SERVICE_UNAVAILABLE');if(!cancelled){setInfo(body);setErrorKey('');await put('meta',{key:'public-info:'+token,value:body})}}).catch(e=>{if(!cancelled&&e.name!=='AbortError')setErrorKey(e.message==='LINK_UNAVAILABLE'?'LINK_UNAVAILABLE':'SERVICE_UNAVAILABLE')})};load();window.addEventListener('online',load);return()=>{cancelled=true;controller.abort();window.removeEventListener('online',load)}},[token]);
 useEffect(()=>{if(entryStage!=='loading'&&entryStage!=='leaving')return;const reduce=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;const timer=setTimeout(()=>setEntryStage(entryStage==='loading'?'leaving':'form'),reduce?0:entryStage==='loading'?2200:320);return()=>clearTimeout(timer)},[entryStage]);
 useEffect(()=>{setTopic(stepTopics[step]);if(entryStage==='form')document.getElementById('enrollment-step-heading')?.focus({preventScroll:true})},[entryStage,step]);
 async function saveDraft(){if(!draftEnabled||!attemptReady)return;try{await put('drafts',{key:'public:'+token,form,step,files:Object.fromEntries(Object.entries(files).map(([key,file])=>[key,{blob:file,name:file.name,type:file.type,lastModified:file.lastModified}])),updated_at:new Date().toISOString()});setDraftMessage('draftSaved')}catch{setErrorKey('draftError')}}
 useEffect(()=>{if(draftReady&&draftEnabled&&!result)void saveDraft()},[draftReady,draftEnabled,form,files,step]);
 async function deleteDraft(){await transaction(['drafts'],'readwrite',tx=>request(tx.objectStore('drafts').delete('public:'+token)));setDraftEnabled(false);setDraftMessage('')}
 useEffect(()=>{if(entryStage!=='form'||step!==5||!info?.turnstileSiteKey)return;let widget:any;let cancelled=false;const render=()=>{if(cancelled||!document.getElementById('captcha'))return;widget=(window as any).turnstile.render('#captcha',{sitekey:info.turnstileSiteKey,action:'enrollment',callback:(v:string)=>setCaptcha(v),'expired-callback':()=>setCaptcha(''),'error-callback':()=>{setCaptcha('');setErrorKey('CAPTCHA_REQUIRED')}})};let script:HTMLScriptElement|undefined;if((window as any).turnstile)render();else{script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.onload=render;script.onerror=()=>setErrorKey('CAPTCHA_REQUIRED');document.head.appendChild(script)}return()=>{cancelled=true;if(widget!==undefined)(window as any).turnstile?.remove(widget);script?.remove();setCaptcha('')}},[step,info,entryStage]);
 function change(key:string,value:any){setForm(current=>({...current,[key]:value}));setErrorKey('')}
 function chooseType(type:string){setForm(current=>({...current,enrollment_type:type}));setErrorKey('')}
 const groups=[['first_name','last_name','birth_date','sex',...(form.has_lrn?['lrn']:[]),'grade_level_id'],['address','contact'],['guardian_name','guardian_contact'],['previous_school']];
 const lrnMessage=lrnState==='invalid'?t.invalidLrn:lrnState==='checking'?t.checking:lrnState==='eligible'?t.eligible:lrnState==='existing_new'?t.existingNew:lrnState==='needs_review'?t.existingReturn:lrnState==='duplicate_application'?t.duplicate:lrnState==='pending'?t.pendingCheck:'';
 async function submit(){if(!navigator.onLine){setErrorKey('offlineSubmit');return;}if(blocked){setErrorKey(lrnState==='existing_new'?'EXISTING_LRN_CONTACT_SCHOOL':'ACTIVE_LRN_APPLICATION');return;}if(!files.photo||!files.certificate){setErrorKey('missingDocument');return;}if(form.has_lrn&&!/^\d{12}$/.test(form.lrn)){setErrorKey('invalidLrn');return;}setBusy(true);setErrorKey('');try{const body=new FormData();body.set('data',JSON.stringify({...form,lrn:form.has_lrn?form.lrn:null,submission_id:submission.current}));body.set('captcha',captcha);for(const [key,file] of Object.entries(files))body.set(key,file);const response=await fetch(endpoint,{method:'POST',headers:{apikey:import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY},body});const received=await response.json();if(!response.ok||received.errorCode){setErrorKey(received.errorCode||'SERVICE_UNAVAILABLE');throw Error('server response')}setResult(received);setTopic('confirmation');await put('meta',{key:'public-attempt:'+token,id:submission.current,result:received});await deleteDraft()}catch(e){if((e as Error).message!=='server response')setErrorKey('SERVICE_UNAVAILABLE');(window as any).turnstile?.reset();setCaptcha('')}finally{setBusy(false)}}
 function advance(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setErrorKey('');const element=event.currentTarget;if(!element.checkValidity()){const invalid=[...element.elements].find(control=>('willValidate' in control)&&(control as HTMLInputElement).willValidate&&!(control as HTMLInputElement).validity.valid) as HTMLElement|undefined;invalid?.setAttribute('aria-invalid','true');invalid?.scrollIntoView?.({block:'center',behavior:window.matchMedia?.('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});invalid?.focus();setErrorKey('requiredError');setTopic('errors');return;}if(step===0&&(blocked||form.has_lrn&&!/^\d{12}$/.test(form.lrn))){setErrorKey(blocked?(lrnState==='existing_new'?'EXISTING_LRN_CONTACT_SCHOOL':'ACTIVE_LRN_APPLICATION'):'invalidLrn');setTopic('lrn');return;}if(step===4&&(!files.photo||!files.certificate)){setErrorKey('missingDocument');setTopic('documents');return;}if(step<5)setStep(step+1);else void submit()}
 async function another(){if(!confirm(t.anotherConfirm))return;const id=uuid();await put('meta',{key:'public-attempt:'+token,id});submission.current=id;setResult(null);setForm(initialForm());setFiles({});setStep(0);setEntryStage('welcome');setErrorKey('')}
 if(result)return <div className="public-page with-guide" lang={language}><div className="public-card confirmation"><Check size={55}/><h1>{t.received}</h1>{error&&<p role="alert">{error}</p>}<p>{t.referenceNote}</p><strong>{result.reference}</strong>{String(result.reference).startsWith('RZM-TEMP-')&&<p>{t.temporary}</p>}<p>{result.lrn_status==='Pending Assignment'?t.pendingAssignment:t.reviewNote}</p><button onClick={()=>window.print()}><Printer size={16}/>{t.print}</button><p>{t.reviewNote}</p><button type="button" onClick={()=>void another().catch(()=>setErrorKey('draftError'))}>{t.startAnother}</button></div>{guide}</div>;
 if(entryStage!=='form')return <div role="main" className={`enrollment-entry ${entryStage==='leaving'?'is-leaving':''}`} lang={language} aria-busy={entryStage!=='welcome'}><div className="enrollment-entry-overlay" aria-hidden="true"/><section className="enrollment-entry-card" aria-live="polite"><img className="enrollment-entry-logo" src="/brand/school-logo.jpg" alt="School seal"/><span className="enrollment-entry-eyebrow">RESTITUTA Z. MEDINA ELEMENTARY SCHOOL</span>{entryStage!=='welcome'?<><h1>{t.preparing}</h1><p>{t.wait}</p><div className="enrollment-entry-progress" role="progressbar" aria-label={t.preparing} aria-valuemin={0} aria-valuemax={100} aria-valuenow={entryStage==='leaving'?100:undefined}><span/></div><p className="enrollment-entry-status">{t.opening}</p></>:<><h1>{t.welcome}</h1><p>{t.welcomeText} {info?.year||'RZM Elementary School'}.</p>{info?.title&&<p className="enrollment-entry-title">{info.title}</p>}{error&&<div className="alert error" role="alert">{error}</div>}<button className="primary enrollment-entry-start" disabled={!info||!attemptReady||errorKey==='LINK_UNAVAILABLE'} onClick={()=>setEntryStage('loading')}>{t.start}<ArrowRight size={19}/></button>{!info&&!error&&<p className="enrollment-entry-status">{t.loading}</p>}</>}</section><div className="enrollment-entry-footer">Restituta Z. Medina Elementary School · Online enrollment</div>{guide}</div>;
 return <div className="public-page enrollment-form-enter enrollment-form-page with-guide" lang={language}><div className="public-brand"><img className="school-brand-logo" src="/brand/school-logo.jpg" alt="School seal"/><span>{info?.school||'RZM Elementary School'}</span></div><div className="enrollment-intro"><span className="eyebrow">RZM ELEMENTARY SCHOOL</span><h1>{t.intro}</h1><p>{t.introText}</p><div className="enrollment-pills"><span><Shield size={14}/>{t.secure}</span><span><ClipboardList size={14}/>{t.six}</span></div></div><div className="public-card"><div className="enrollment-card-heading"><div><span className="eyebrow">ONLINE ENROLLMENT · {info?.year}</span><h1>{info?.title||'RZM Enrollment'}</h1></div><span className="form-step-count">{step+1} / 6</span></div>{error&&<div id="enrollment-form-error" className="alert error" role="alert">{error}</div>}{info&&<><div className="enrollment-progress" role="progressbar" aria-label={t.step} aria-valuemin={1} aria-valuemax={6} aria-valuenow={step+1}><span style={{width:`${(step+1)/6*100}%`}}/></div><div className="steps">{t.titles.map((title,i)=><div key={i} aria-current={i===step?'step':undefined} className={i===step?'current':i<step?'done':''}><b>{i<step?'✓':i+1}</b><small>{title}</small></div>)}</div>{info.instructions&&<p>{info.instructions}</p>}<div className="form-section-heading"><span className="section-number">0{step+1}</span><div><h2 tabIndex={-1} id="enrollment-step-heading">{t.titles[step]}</h2><p>{t.descriptions[step]}</p></div></div><form noValidate key={step} className="enrollment-step-enter" onSubmit={advance} onChange={e=>{const input=e.target as unknown as HTMLInputElement;if(input.validity?.valid)input.removeAttribute('aria-invalid')}}>
 {step===0&&<><fieldset className="learner-type"><legend>{t.type}<FieldHelp topic="type" language={language} open={help}/></legend><div className="learner-options">{[['New',t.newLearner],['Returning',t.returnLearner]].map(([value,title])=><label className={(value==='New'?form.enrollment_type==='New':form.enrollment_type!=='New')?'chosen':''} key={value}><input type="radio" name="learner-type" checked={value==='New'?form.enrollment_type==='New':form.enrollment_type!=='New'} onChange={()=>chooseType(value)}/><span>{title}</span></label>)}</div>{form.enrollment_type!=='New'&&<div className="returning-options">{[['Returning',t.returning],['Transferee',t.transferee]].map(([value,title])=><label key={value}><input type="radio" name="returning-type" checked={form.enrollment_type===value} onChange={()=>chooseType(value)}/>{title}</label>)}</div>}{form.enrollment_type==='New'&&<p>{t.firstQuestion}</p>}</fieldset><fieldset className="lrn-choice"><legend>{t.hasQuestion}<FieldHelp topic="lrn" language={language} open={help}/></legend>{[[true,t.yes],[false,t.no]].map(([value,title])=><label key={String(value)}><input type="radio" name="has-lrn" checked={form.has_lrn===value} onChange={()=>setForm(current=>({...current,has_lrn:value,lrn:value?current.lrn:''}))}/>{String(title)}</label>)}</fieldset>{!form.has_lrn&&<div className="lrn-notice" role="status"><strong>{form.enrollment_type==='New'?t.pendingAssignment:t.pendingCheck}</strong><p>{form.enrollment_type==='New'?t.pendingExplanation:t.unknownExplanation}</p></div>}</>}
 <div className="form-grid">{step<4&&groups[step].map(key=><div className="enrollment-field" key={key}><div className="field-caption"><label htmlFor={'enroll-'+key}>{(t as any)[key]||t[key as keyof typeof t] as string} <small>{key==='previous_school'?t.optional:t.required}</small></label><FieldHelp topic={fieldTopics[key]||stepTopics[step]} language={language} open={help}/></div>{['sex','grade_level_id'].includes(key)?<select id={'enroll-'+key} required value={form[key]||''} onChange={e=>change(key,e.target.value)}><option value="">{t.select}</option>{(key==='grade_level_id'?info.grades:[{id:'Male',name:t.male},{id:'Female',name:t.female}]).map((option:Row)=><option key={option.id} value={option.id}>{option.name}</option>)}</select>:<input id={'enroll-'+key} placeholder={key==='lrn'?'000000000000':undefined} autoComplete={key==='address'?'street-address':['contact','guardian_contact'].includes(key)?'tel':'off'} inputMode={['lrn','contact','guardian_contact'].includes(key)?'numeric':undefined} type={key==='birth_date'?'date':['contact','guardian_contact'].includes(key)?'tel':'text'} max={key==='birth_date'?new Date().toISOString().slice(0,10):undefined} maxLength={key==='lrn'?12:300} pattern={key==='lrn'?'[0-9]{12}':undefined} required={key!=='previous_school'} value={form[key]||''} aria-describedby={key==='lrn'?'lrn-message':undefined} aria-invalid={key==='lrn'&&(blocked||lrnState==='invalid')?true:undefined} onChange={e=>change(key,key==='lrn'?lrnDigits(e.target.value):e.target.value)}/ >}{key==='lrn'&&<small id="lrn-message" role="status" aria-live="polite" className={blocked||lrnState==='invalid'?'lrn-warning':'lrn-check'}>{lrnMessage}</small>}</div>)}{step===3&&(info.extra_questions||[]).map((question:string)=><label key={question}>{question}<input maxLength={1000} value={form.extra_answers?.[question]||''} onChange={e=>change('extra_answers',{...form.extra_answers,[question]:e.target.value})}/></label>)}{step===4&&[['photo',t.photo],['certificate',t.certificate]].map(([key,title])=><div className="upload-card" key={key}><div className="field-caption"><label htmlFor={'upload-'+key}>{title}</label><FieldHelp topic="documents" language={language} open={help}/></div><span className="upload-icon"><Download size={23}/></span><input id={'upload-'+key} type="file" accept={key==='photo'?'image/jpeg,image/png':'image/jpeg,image/png,application/pdf'} required={!files[key]} onChange={e=>{const file=e.target.files?.[0];if(file&&file.size>0&&file.size<=5242880&&(key==='photo'?['image/jpeg','image/png']:['image/jpeg','image/png','application/pdf']).includes(file.type)){setFiles(current=>({...current,[key]:file}));setErrorKey('')}else{setFiles(current=>{const next={...current};delete next[key];return next});setErrorKey('badDocument');e.target.value=''}}}/><small>{files[key]?.name||'JPG / PNG'+(key==='certificate'?' / PDF':'')+' · 5 MB'}</small></div>)}</div>
 {step===5&&<><div className="profile-grid">{Object.entries(form).filter(([key])=>key!=='has_lrn').map(([key,value])=><div key={key}><small>{(t as any)[key]||key}</small><p>{key==='grade_level_id'?info.grades.find((g:Row)=>g.id===value)?.name:key==='enrollment_type'?value==='New'?t.newLearner:value==='Returning'?t.returning:t.transferee:key==='extra_answers'?Object.entries(value||{}).map(([q,a])=><span key={q}>{q}: {String(a)}<br/></span>):key==='lrn'&&!value?t.noLrnReview:String(value||'—')}</p></div>)}{Object.entries(files).map(([key,file])=><div key={key}><small>{key==='photo'?t.photo:t.certificate}</small><p>{file.name}</p></div>)}</div><label className="consent"><input type="checkbox" required/>{t.consent}</label><div id="captcha"/>{!info.turnstileSiteKey&&<p className="alert error">{t.captchaMissing}</p>}</>}
 <div className="toolbar enrollment-actions"><button type="button" disabled={step===0||busy} onClick={()=>{setErrorKey('');setStep(step-1)}}>{t.back}</button><span>{t.step} {step+1} {t.of} 6</span><button className="primary" disabled={busy||!attemptReady||(step===5&&(!captcha||blocked))}>{busy?t.submitting:step===5?t.submit:t.next}<ArrowRight size={16}/></button></div></form></>}
 <section className="draft-controls"><label><input type="checkbox" checked={draftEnabled} onChange={e=>{if(e.target.checked)setDraftEnabled(true);else void deleteDraft().catch(()=>setErrorKey('draftError'))}}/>{t.draftConsent}</label><small>{t.draftPrivacy}</small>{draftEnabled&&<><p role="status">{(t as any)[draftMessage]}</p><button type="button" onClick={()=>void saveDraft()}>{t.saveDraft}</button><button type="button" onClick={()=>{if(confirm(t.clearConfirm))void deleteDraft().catch(()=>setErrorKey('draftError'))}}>{t.clearDraft}</button></>}</section></div><p className="public-footer">{t.assistance}</p>{guide}</div>
}
