create table public.profiles(id uuid primary key references auth.users on delete cascade, full_name text not null, role text not null check(role in ('admin','teacher')), can_grade boolean not null default false);
create function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from profiles where id=auth.uid() and role='admin') $$;
create table public.school_settings(id int primary key default 1 check(id=1), school_name text not null default 'Restituta Z. Medina Elementary School', pass_mark numeric not null default 75 check(pass_mark between 0 and 100));
insert into school_settings(id) values(1);
create table public.school_years(id uuid primary key default gen_random_uuid(), name text unique not null, active boolean default false);
create unique index one_active_year on school_years(active) where active;
create table public.grade_levels(id uuid primary key default gen_random_uuid(), name text unique not null, rank int unique not null);
create table public.sections(id uuid primary key default gen_random_uuid(), name text not null, grade_level_id uuid not null references grade_levels, school_year_id uuid not null references school_years, unique(name,grade_level_id,school_year_id));
create table public.subjects(id uuid primary key default gen_random_uuid(), name text not null, grade_level_id uuid not null references grade_levels, unique(name,grade_level_id));
create table public.assignments(id uuid primary key default gen_random_uuid(), teacher_id uuid not null references profiles, section_id uuid not null references sections, subject_id uuid not null references subjects, unique(teacher_id,section_id,subject_id));
create table public.students(id uuid primary key default gen_random_uuid(), lrn text unique check(lrn is null or lrn ~ '^[0-9]{12}$'), first_name text not null, last_name text not null, birth_date date not null, sex text not null check(sex in ('Male','Female')), address text not null, contact text not null, guardian_name text not null, guardian_contact text not null, created_at timestamptz not null default now());
create table public.enrollment_links(id uuid primary key default gen_random_uuid(), token uuid unique not null default gen_random_uuid(), title text not null, school_year_id uuid not null references school_years, allowed_grade_ids uuid[] not null, published boolean default false, archived boolean default false, opens_at timestamptz not null, closes_at timestamptz not null, check(closes_at>opens_at), check(cardinality(allowed_grade_ids)>0));
create table public.applications(id uuid primary key default gen_random_uuid(), reference text unique not null default ('RZM-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,16))), link_id uuid not null references enrollment_links, grade_level_id uuid not null references grade_levels, lrn text check(lrn is null or lrn ~ '^[0-9]{12}$'), first_name text not null, last_name text not null, birth_date date not null, sex text not null check(sex in ('Male','Female')), address text not null, contact text not null, guardian_name text not null, guardian_contact text not null, previous_school text default '', enrollment_type text not null check(enrollment_type in ('New','Returning','Transferee')), status text not null default 'Pending' check(status in ('Pending','Under Review','Approved','Enrolled','Incomplete','Rejected')), note text default '', student_id uuid references students, created_at timestamptz default now());
create unique index one_application_lrn on applications(link_id,lrn) where lrn is not null and status<>'Rejected';
create table public.documents(id uuid primary key default gen_random_uuid(), application_id uuid not null references applications on delete cascade, kind text not null check(kind in ('Photo','Birth Certificate')), path text unique not null);
create table public.enrollments(id uuid primary key default gen_random_uuid(), student_id uuid not null references students, school_year_id uuid not null references school_years, grade_level_id uuid not null references grade_levels, section_id uuid not null references sections, unique(student_id,school_year_id));
create table public.grades(id uuid primary key default gen_random_uuid(), enrollment_id uuid not null references enrollments on delete cascade, subject_id uuid not null references subjects, q1 numeric check(q1 between 0 and 100), q2 numeric check(q2 between 0 and 100), q3 numeric check(q3 between 0 and 100), q4 numeric check(q4 between 0 and 100), final_grade numeric generated always as (round((q1+q2+q3+q4)/4,0)) stored, unique(enrollment_id,subject_id));
create table public.audit_logs(id bigint generated always as identity primary key, actor uuid, action text not null, table_name text not null, record_id text, created_at timestamptz default now());
create function public.audit_change() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into audit_logs(actor,action,table_name,record_id) values(auth.uid(),TG_OP,TG_TABLE_NAME,coalesce(to_jsonb(new)->>'id',to_jsonb(old)->>'id')); return coalesce(new,old); end $$;
create function public.can_view_enrollment(e uuid) returns boolean language sql stable security definer set search_path=public as $$ select is_admin() or exists(select 1 from enrollments n join assignments a on a.section_id=n.section_id where n.id=e and a.teacher_id=auth.uid()) $$;
create function public.can_edit_grade(e uuid,s uuid) returns boolean language sql stable security definer set search_path=public as $$ select is_admin() or exists(select 1 from enrollments n join assignments a on a.section_id=n.section_id join profiles p on p.id=a.teacher_id where n.id=e and a.subject_id=s and p.id=auth.uid() and p.can_grade) $$;
create function public.validate_enrollment() returns trigger language plpgsql set search_path=public as $$ begin if not exists(select 1 from sections where id=new.section_id and grade_level_id=new.grade_level_id and school_year_id=new.school_year_id) then raise exception 'Section must match grade and school year'; end if; return new; end $$;
create trigger enrollment_validate before insert or update on enrollments for each row execute function validate_enrollment();
create function public.assign_subjects() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into grades(enrollment_id,subject_id) select new.id,id from subjects where grade_level_id=new.grade_level_id on conflict do nothing; return new; end $$;
create trigger enrollment_subjects after insert on enrollments for each row execute function assign_subjects();
create function public.approve_application(application uuid, section uuid) returns uuid language plpgsql security definer set search_path=public as $$ declare a applications; s uuid; y uuid; begin if not is_admin() then raise exception 'Admin access required'; end if; select * into a from applications where id=application for update; if a.id is null or a.status in ('Approved','Enrolled','Rejected') then raise exception 'Application cannot be approved'; end if; select school_year_id into y from enrollment_links where id=a.link_id; if not exists(select 1 from sections where id=section and grade_level_id=a.grade_level_id and school_year_id=y) then raise exception 'Choose a section for this grade and year'; end if; if a.lrn is not null then select id into s from students where lrn=a.lrn; end if; if s is null then insert into students(lrn,first_name,last_name,birth_date,sex,address,contact,guardian_name,guardian_contact) values(a.lrn,a.first_name,a.last_name,a.birth_date,a.sex,a.address,a.contact,a.guardian_name,a.guardian_contact) returning id into s; else update students set first_name=a.first_name,last_name=a.last_name,birth_date=a.birth_date,sex=a.sex,address=a.address,contact=a.contact,guardian_name=a.guardian_name,guardian_contact=a.guardian_contact where id=s; end if; insert into enrollments(student_id,school_year_id,grade_level_id,section_id) values(s,y,a.grade_level_id,section); update applications set status='Enrolled',student_id=s where id=a.id; return s; end $$;
create function public.promote_student(enrollment uuid, target_year uuid, target_section uuid) returns uuid language plpgsql security definer set search_path=public as $$ declare n enrollments; g uuid; result uuid; threshold numeric; begin if not is_admin() then raise exception 'Admin access required'; end if; select * into n from enrollments where id=enrollment for update; select pass_mark into threshold from school_settings where id=1; if n.id is null or n.school_year_id=target_year then raise exception 'Choose a different school year'; end if; if not exists(select 1 from grades where enrollment_id=n.id) or exists(select 1 from grades where enrollment_id=n.id and (final_grade is null or final_grade<threshold)) then raise exception 'All subjects need complete passing grades'; end if; select id into g from grade_levels where rank=(select rank+1 from grade_levels where id=n.grade_level_id); if g is null then raise exception 'No next grade level'; end if; insert into enrollments(student_id,school_year_id,grade_level_id,section_id) values(n.student_id,target_year,g,target_section) returning id into result; return result; end $$;
-- Deny public access to personal data. Only the Edge Function accepts public applications.
do $$ declare t text; begin foreach t in array array['profiles','school_settings','school_years','grade_levels','sections','subjects','assignments','students','enrollment_links','applications','documents','enrollments','grades','audit_logs'] loop execute format('alter table public.%I enable row level security',t); execute format('create policy admin_all on public.%I for all to authenticated using (public.is_admin()) with check (public.is_admin())',t); if t<>'audit_logs' then execute format('create trigger audit after insert or update or delete on public.%I for each row execute function public.audit_change()',t); end if; end loop; end $$;
drop policy admin_all on audit_logs;
create policy admin_audit_read on audit_logs for select to authenticated using(is_admin());
create policy self_profile on profiles for select to authenticated using(id=auth.uid());
create policy teacher_students on students for select to authenticated using(exists(select 1 from enrollments e where e.student_id=students.id and can_view_enrollment(e.id)));
create policy teacher_enrollments on enrollments for select to authenticated using(can_view_enrollment(id));
create policy teacher_grades on grades for select to authenticated using(can_view_enrollment(enrollment_id));
create policy teacher_grade_update on grades for update to authenticated using(can_edit_grade(enrollment_id,subject_id)) with check(can_edit_grade(enrollment_id,subject_id));
-- Teachers can only update quarterly grade columns, not change student/subject associations.
revoke update on grades from authenticated;
grant update(q1,q2,q3,q4) on grades to authenticated;
create policy teacher_assignments on assignments for select to authenticated using(teacher_id=auth.uid());
do $$ declare t text; begin foreach t in array array['school_settings','school_years','grade_levels','sections','subjects'] loop execute format('create policy staff_read on public.%I for select to authenticated using (exists(select 1 from profiles where id=auth.uid()))',t); end loop; end $$;
revoke all on function approve_application(uuid,uuid),promote_student(uuid,uuid,uuid) from public;
grant execute on function approve_application(uuid,uuid),promote_student(uuid,uuid,uuid) to authenticated;
insert into grade_levels(name,rank) values('Kindergarten',0),('Grade 1',1),('Grade 2',2),('Grade 3',3),('Grade 4',4),('Grade 5',5),('Grade 6',6);
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('student-documents','student-documents',false,5242880,array['image/jpeg','image/png','application/pdf']);
create policy admin_documents on storage.objects for all to authenticated using(bucket_id='student-documents' and is_admin()) with check(bucket_id='student-documents' and is_admin());
create function public.validate_assignment() returns trigger language plpgsql set search_path=public as $$ begin if not exists(select 1 from sections s join subjects u on u.grade_level_id=s.grade_level_id where s.id=new.section_id and u.id=new.subject_id) or not exists(select 1 from profiles where id=new.teacher_id and role='teacher') then raise exception 'Assign a teacher and subject for the section grade level'; end if; return new; end $$;
create trigger assignment_validate before insert or update on assignments for each row execute function validate_assignment();
create function public.validate_grade() returns trigger language plpgsql set search_path=public as $$ begin if not exists(select 1 from enrollments e join subjects s on s.grade_level_id=e.grade_level_id where e.id=new.enrollment_id and s.id=new.subject_id) then raise exception 'Subject must match the enrolled grade level'; end if; return new; end $$;
create trigger grade_validate before insert or update on grades for each row execute function validate_grade();
create function public.backfill_subject() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into grades(enrollment_id,subject_id) select id,new.id from enrollments where grade_level_id=new.grade_level_id on conflict do nothing; return new; end $$;
create trigger subject_backfill after insert on subjects for each row execute function backfill_subject();
-- Structural changes would invalidate saved academic history. Create new records instead.
create function public.protect_history() returns trigger language plpgsql set search_path=public as $$ begin
 if TG_TABLE_NAME='enrollments' then
  if new.grade_level_id<>old.grade_level_id or new.school_year_id<>old.school_year_id or new.student_id<>old.student_id then raise exception 'Preserve enrollment history; create a new enrollment'; end if;
 elsif TG_TABLE_NAME='subjects' then
  if new.grade_level_id<>old.grade_level_id and exists(select 1 from grades where subject_id=old.id) then raise exception 'Subject has academic history; create a new subject'; end if;
 elsif TG_TABLE_NAME='sections' then
  if (new.grade_level_id<>old.grade_level_id or new.school_year_id<>old.school_year_id) and exists(select 1 from enrollments where section_id=old.id) then raise exception 'Section has enrollment history; create a new section'; end if;
 end if; return new; end $$;
create trigger protect_enrollment before update on enrollments for each row execute function protect_history();
create trigger protect_subject before update on subjects for each row execute function protect_history();
create trigger protect_section before update on sections for each row execute function protect_history();
alter table enrollment_links add column instructions text not null default '', add column extra_questions text[] not null default '{}';
alter table applications add column extra_answers jsonb not null default '{}'::jsonb;
